ALTER TABLE "WorkspaceSettings"
  ADD COLUMN "reportPrimary" TEXT NOT NULL DEFAULT '#174C72',
  ADD COLUMN "reportAccent" TEXT NOT NULL DEFAULT '#2E7EAA',
  ADD COLUMN "reportSoft" TEXT NOT NULL DEFAULT '#EDF5F9';
