/**
 * Writes the SQL that publishes HINTEK's built-in inspection forms as version 1 (Daniel 2026-09-26).
 * Usage: npx tsx scripts/forms/builtin-forms-migration.ts > prisma/migrations/<name>/migration.sql
 * The SQL is idempotent (ON CONFLICT DO NOTHING), so a form the superadmin later changed or deleted is never touched
 * again by a new deploy.
 */
import { createHash } from "node:crypto";
import { BUILTIN_FORMS } from "../../lib/workflow/builtin-forms";
import { formDocumentSchema } from "../../lib/workflow/form-document";

const literal = (value: string) => `'${value.replace(/'/g, "''")}'`;
const json = (value: unknown) => `${literal(JSON.stringify(value))}::jsonb`;
const actor = "system:hintek";

const lines = [
  "-- HINTEK's built-in inspection types (Daniel 2026-09-26): Termografering, Fortlöpande kontroll, Isolationsmätning – EBR",
  "-- and Följelinemätning – EBR, published once as version 1 of ordinary forms. Generated by",
  "-- scripts/forms/builtin-forms-migration.ts from lib/workflow/builtin-forms.ts. Idempotent: an existing id is left as it is.",
];
for (const form of BUILTIN_FORMS) {
  const document = formDocumentSchema.parse(form.document);
  const hash = createHash("sha256").update(JSON.stringify(document)).digest("hex");
  const meta = form.meta;
  lines.push("",
    `INSERT INTO "FormTemplate" ("id", "name", "displayName", "description", "internalNote", "color", "icon", "category", "allowStandalone", "allowInProject", "status", "draft", "draftRevision", "publishedVersion", "createdBy", "updatedBy", "createdAt", "updatedAt")`,
    `VALUES (${literal(form.id)}, ${literal(meta.name)}, ${literal(meta.displayName)}, ${literal(meta.description)}, ${literal("Levereras av HINTEK (inbyggd kontrolltyp).")}, ${literal(meta.color)}, ${literal(meta.icon)}, ${literal(meta.category)}, ${meta.allowStandalone}, ${meta.allowInProject}, 'PUBLISHED', ${json(document)}, 1, 1, ${literal(actor)}, ${literal(actor)}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)`,
    `ON CONFLICT ("id") DO NOTHING;`,
    `INSERT INTO "FormTemplateVersion" ("id", "templateId", "version", "name", "displayName", "description", "color", "icon", "category", "allowStandalone", "allowInProject", "document", "hash", "publishedBy", "createdAt")`,
    `SELECT ${literal(`${form.id}-v1`)}, ${literal(form.id)}, 1, ${literal(meta.name)}, ${literal(meta.displayName)}, ${literal(meta.description)}, ${literal(meta.color)}, ${literal(meta.icon)}, ${literal(meta.category)}, ${meta.allowStandalone}, ${meta.allowInProject}, ${json(document)}, ${literal(hash)}, ${literal(actor)}, CURRENT_TIMESTAMP`,
    `WHERE NOT EXISTS (SELECT 1 FROM "FormTemplateVersion" WHERE "templateId" = ${literal(form.id)});`,
    `INSERT INTO "FormTemplateEvent" ("id", "templateId", "action", "summary", "actorUserId", "actorName", "createdAt")`,
    `SELECT ${literal(`${form.id}-published-v1`)}, ${literal(form.id)}, 'PUBLISHED', 'Version 1 publicerades av HINTEK', ${literal(actor)}, 'HINTEK', CURRENT_TIMESTAMP`,
    `WHERE NOT EXISTS (SELECT 1 FROM "FormTemplateEvent" WHERE "id" = ${literal(`${form.id}-published-v1`)});`,
  );
}
process.stdout.write(`${lines.join("\n")}\n`);
