/**
 * Writes the SQL that releases HINTEK's built-in forms as they are in the code (2026-09-28): a new form is created and
 * published as version 1; a changed form gets a new published version. Existing protocols keep their version.
 * Usage: npx tsx scripts/forms/builtin-release-migration.ts <label> [form id …] > prisma/migrations/<name>/migration.sql
 *
 * HINTEK_OVERWRITE=1 releases a template even when the superadmin changed it last (2026-10-02, explicit permission).
 * Idempotent and careful: a form is only touched while HINTEK's template was last written by the system
 * (`updatedBy = 'system:hintek'`) – a form the superadmin has changed, unpublished or deleted is left alone – and a
 * version with the same content is never published twice. Companies' own versions are never touched.
 */
import { createHash } from "node:crypto";
import { BUILTIN_FORMS, type BuiltinForm } from "../../lib/workflow/builtin-forms";
import { kfidForm } from "../../lib/workflow/builtin-kfid-form";
import { riskForm } from "../../lib/workflow/builtin-risk-form";
import { ROUND_FORMS } from "../../lib/workflow/builtin-rounds";
import { formDocumentSchema } from "../../lib/workflow/form-document";

const literal = (value: string) => `'${value.replace(/'/g, "''")}'`;
const json = (value: unknown) => `${literal(JSON.stringify(value))}::jsonb`;
const actor = "system:hintek";
const [label = "release", ...only] = process.argv.slice(2);
/**
 * Versions HINTEK delivered that a superadmin published unchanged (verified 2026-09-28 against the code at e17a3f8): a
 * template whose draft equals such a published version has no changes of its own and may be released on.
 */
const DELIVERED: Record<string, string[]> = {
  "hintek-kontroll-fore-idrifttagning": ["508695408a65ea378bcbd4d9a255671ad2a7d357772bb5dc417fa07fb6ea12f6"],
  "hintek-riskbedomning": ["8900c48d21b2de66ae99eb5131e9ec0fa17e4ac592889cd06ba4d3cdd6cd2dce", "537da0a350ed2ac7c8a9c340fcbff63b2b1f90e1680884c9c00ee048ba8be1db"],
};
const forms: (BuiltinForm & { permissionArea?: string })[] = [
  { ...kfidForm, permissionArea: "kfid" }, { ...riskForm, permissionArea: "risk-assessment" }, ...BUILTIN_FORMS, ...ROUND_FORMS,
].filter((form) => !only.length || only.includes(form.id));

const lines = [
  `-- HINTEK's built-in forms released from the code (${label}). Generated by scripts/forms/builtin-release-migration.ts.`,
  "-- Only a HINTEK template last written by the system is touched; a version with the same content is never published twice.",
];
for (const form of forms) {
  const document = formDocumentSchema.parse(form.document);
  const hash = createHash("sha256").update(JSON.stringify(document)).digest("hex");
  const meta = form.meta;
  const template = literal(form.id);
  // A release is its content and its card (name, category …): a new category alone is a new version too.
  const release = createHash("sha256").update(JSON.stringify({ hash, meta: [meta.name, meta.displayName, meta.description, meta.color, meta.icon, meta.category, meta.allowStandalone, meta.allowInProject] })).digest("hex");
  const versionId = literal(`${form.id}-${release.slice(0, 12)}`);
  const same = `"templateId" = ${template} AND "hash" = ${literal(hash)} AND "name" = ${literal(meta.name)} AND "displayName" = ${literal(meta.displayName)} AND "description" = ${literal(meta.description)} AND "color" = ${literal(meta.color)} AND "icon" = ${literal(meta.icon)} AND "category" = ${literal(meta.category)} AND "allowStandalone" = ${meta.allowStandalone} AND "allowInProject" = ${meta.allowInProject}`;
  const versionOf = `(SELECT MAX("version") FROM "FormTemplateVersion" WHERE ${same})`;
  const published = (column: string) => `(SELECT v."${column}" FROM "FormTemplateVersion" v WHERE v."templateId" = t."id" AND v."version" = t."publishedVersion")`;
  const delivered = DELIVERED[form.id]?.length ? ` OR (t."draft" = ${published("document")} AND ${published("hash")} IN (${DELIVERED[form.id].map(literal).join(", ")}))` : "";
  // HINTEK_OVERWRITE=1 (2026-10-02, explicit permission: the superadmin's edits of HINTEK's own templates are tests
  // and may be overwritten): the template is released whoever changed it last. Companies' own versions are never touched.
  const untouched = process.env.HINTEK_OVERWRITE === "1" ? `t."id" = ${template} AND t."organizationId" IS NULL` : `t."id" = ${template} AND t."organizationId" IS NULL AND (t."updatedBy" = ${literal(actor)}${delivered})`;
  lines.push("", `-- ${meta.name}`,
    `INSERT INTO "FormTemplate" ("id", "name", "displayName", "description", "internalNote", "color", "icon", "category", "allowStandalone", "allowInProject", "permissionArea", "origin", "authorName", "status", "draft", "draftRevision", "createdBy", "updatedBy", "createdAt", "updatedAt")`,
    `VALUES (${template}, ${literal(meta.name)}, ${literal(meta.displayName)}, ${literal(meta.description)}, ${literal("Levereras av HINTEK (inbyggd kontrolltyp).")}, ${literal(meta.color)}, ${literal(meta.icon)}, ${literal(meta.category)}, ${meta.allowStandalone}, ${meta.allowInProject}, ${literal(form.permissionArea ?? "forms")}, 'HINTEK', 'HINTEK', 'PUBLISHED', ${json(document)}, 1, ${literal(actor)}, ${literal(actor)}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)`,
    `ON CONFLICT ("id") DO NOTHING;`,
    `INSERT INTO "FormTemplateVersion" ("id", "templateId", "version", "name", "displayName", "description", "color", "icon", "category", "allowStandalone", "allowInProject", "document", "hash", "publishedBy", "publisherName", "createdAt")`,
    `SELECT ${versionId}, t."id", (SELECT COALESCE(MAX("version"), 0) + 1 FROM "FormTemplateVersion" WHERE "templateId" = ${template}), ${literal(meta.name)}, ${literal(meta.displayName)}, ${literal(meta.description)}, ${literal(meta.color)}, ${literal(meta.icon)}, ${literal(meta.category)}, ${meta.allowStandalone}, ${meta.allowInProject}, ${json(document)}, ${literal(hash)}, ${literal(actor)}, 'HINTEK', CURRENT_TIMESTAMP`,
    `FROM "FormTemplate" t WHERE ${untouched} AND t."status" = 'PUBLISHED'`,
    `AND NOT EXISTS (SELECT 1 FROM "FormTemplateVersion" WHERE ${same});`,
    `UPDATE "FormTemplate" AS t SET "draft" = ${json(document)}, "draftRevision" = "draftRevision" + 1, "publishedVersion" = ${versionOf}, "name" = ${literal(meta.name)}, "displayName" = ${literal(meta.displayName)}, "description" = ${literal(meta.description)}, "color" = ${literal(meta.color)}, "icon" = ${literal(meta.icon)}, "category" = ${literal(meta.category)}, "allowStandalone" = ${meta.allowStandalone}, "allowInProject" = ${meta.allowInProject}, "updatedBy" = ${literal(actor)}, "updatedAt" = CURRENT_TIMESTAMP`,
    `WHERE ${untouched} AND ${versionOf} IS NOT NULL AND t."publishedVersion" IS DISTINCT FROM ${versionOf};`,
    `INSERT INTO "FormTemplateEvent" ("id", "templateId", "action", "summary", "actorUserId", "actorName", "createdAt")`,
    `SELECT ${versionId}, ${template}, 'PUBLISHED', 'Version ' || ${versionOf} || ' publicerades av HINTEK (${label.replace(/'/g, "''")})', ${literal(actor)}, 'HINTEK', CURRENT_TIMESTAMP`,
    `WHERE ${versionOf} IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "FormTemplateEvent" WHERE "id" = ${versionId});`,
  );
}
process.stdout.write(`${lines.join("\n")}\n`);
