/**
 * Writes the SQL that brings HINTEK's originals of Kontroll före idrifttagning and Riskbedömning up to the current
 * documents in lib/workflow (2026-09-27: in the task they must look exactly like the original editors).
 * Usage: npx tsx scripts/forms/builtin-originals-update-migration.ts <revision> > prisma/migrations/<name>/migration.sql
 * Idempotent and careful: only a draft still at the revision the previous deploy left (<revision>) is replaced, so a
 * draft the superadmin has changed is never overwritten. A published original keeps its published version; the new
 * draft is published by HINTEK in Skapa formulär (version 2).
 */
import { kfidForm } from "../../lib/workflow/builtin-kfid-form";
import { riskForm } from "../../lib/workflow/builtin-risk-form";
import { formDocumentSchema } from "../../lib/workflow/form-document";

const literal = (value: string) => `'${value.replace(/'/g, "''")}'`;
const json = (value: unknown) => `${literal(JSON.stringify(value))}::jsonb`;
const actor = "system:hintek";
const revision = Number(process.argv[2] || 1);

const lines = [
  "-- HINTEK's originals of Kontroll före idrifttagning and Riskbedömning: the task view exactly like the original editors (2026-09-27).",
  "-- Generated by scripts/forms/builtin-originals-update-migration.ts from lib/workflow/builtin-kfid-form.ts and builtin-risk-form.ts.",
  `-- Only a draft still at revision ${revision} (untouched since the previous deploy) is replaced; published versions are never changed.`,
];
for (const form of [kfidForm, riskForm]) {
  const document = formDocumentSchema.parse(form.document);
  lines.push("",
    `UPDATE "FormTemplate" SET "draft" = ${json(document)}, "draftRevision" = ${revision + 1}, "updatedBy" = ${literal(actor)}, "updatedAt" = CURRENT_TIMESTAMP`,
    `WHERE "id" = ${literal(form.id)} AND "organizationId" IS NULL AND "draftRevision" = ${revision};`,
    `INSERT INTO "FormTemplateEvent" ("id", "templateId", "action", "summary", "actorUserId", "actorName", "createdAt")`,
    `SELECT ${literal(`${form.id}-task-look-${revision + 1}`)}, ${literal(form.id)}, 'UPDATED', 'HINTEK uppdaterade utkastet: uppgiften ser ut som originalet (leverans ${revision + 1})', ${literal(actor)}, 'HINTEK', CURRENT_TIMESTAMP`,
    `WHERE EXISTS (SELECT 1 FROM "FormTemplate" WHERE "id" = ${literal(form.id)} AND "draftRevision" = ${revision + 1} AND "updatedBy" = ${literal(actor)})`,
    `AND NOT EXISTS (SELECT 1 FROM "FormTemplateEvent" WHERE "id" = ${literal(`${form.id}-task-look-${revision + 1}`)});`,
  );
}
process.stdout.write(`${lines.join("\n")}\n`);
