/**
 * Writes the SQL that stores HINTEK's originals of Kontroll före idrifttagning and Riskbedömning as form drafts
 * (Daniel 2026-09-27, decision B). They stay drafts – not under Ny uppgift – until the switch-over publishes them.
 * Usage: npx tsx scripts/forms/builtin-originals-migration.ts > prisma/migrations/<name>/migration.sql
 * Idempotent (ON CONFLICT DO NOTHING): a draft the superadmin has since changed is never touched by a new deploy.
 */
import { kfidForm } from "../../lib/workflow/builtin-kfid-form";
import { riskForm } from "../../lib/workflow/builtin-risk-form";
import { formDocumentSchema } from "../../lib/workflow/form-document";

const literal = (value: string) => `'${value.replace(/'/g, "''")}'`;
const json = (value: unknown) => `${literal(JSON.stringify(value))}::jsonb`;
const actor = "system:hintek";

const lines = [
  "-- HINTEK's originals of Kontroll före idrifttagning and Riskbedömning as form drafts (Daniel 2026-09-27, decision B).",
  "-- Generated by scripts/forms/builtin-originals-migration.ts from lib/workflow/builtin-kfid-form.ts and builtin-risk-form.ts.",
  "-- Drafts only: nothing appears under Ny uppgift until the switch-over. Idempotent: an existing id is left as it is.",
];
for (const form of [kfidForm, riskForm]) {
  const document = formDocumentSchema.parse(form.document);
  const meta = form.meta;
  lines.push("",
    `INSERT INTO "FormTemplate" ("id", "name", "displayName", "description", "internalNote", "color", "icon", "category", "allowStandalone", "allowInProject", "status", "draft", "draftRevision", "publishedVersion", "createdBy", "updatedBy", "createdAt", "updatedAt")`,
    `VALUES (${literal(form.id)}, ${literal(meta.name)}, ${literal(meta.displayName)}, ${literal(meta.description)}, ${literal("HINTEK:s original, byggt av formulärskaparens byggstenar. Publiceras vid övergången från den inbyggda typen.")}, ${literal(meta.color)}, ${literal(meta.icon)}, ${literal(meta.category)}, ${meta.allowStandalone}, ${meta.allowInProject}, 'DRAFT', ${json(document)}, 1, NULL, ${literal(actor)}, ${literal(actor)}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)`,
    `ON CONFLICT ("id") DO NOTHING;`,
    `INSERT INTO "FormTemplateEvent" ("id", "templateId", "action", "summary", "actorUserId", "actorName", "createdAt")`,
    `SELECT ${literal(`${form.id}-created`)}, ${literal(form.id)}, 'CREATED', 'Originalet lades in av HINTEK som utkast', ${literal(actor)}, 'HINTEK', CURRENT_TIMESTAMP`,
    `WHERE NOT EXISTS (SELECT 1 FROM "FormTemplateEvent" WHERE "id" = ${literal(`${form.id}-created`)});`,
  );
}
process.stdout.write(`${lines.join("\n")}\n`);
