/**
 * Writes the SQL that publishes HINTEK's originals of Kontroll före idrifttagning and Riskbedömning as ordinary
 * forms (Daniel 2026-09-28: "inga utkast – alla är original"). From then on the built-in control and risk assessment
 * are made with these forms everywhere; the old editors stay only for existing records.
 * Usage: npx tsx scripts/forms/builtin-originals-publish-migration.ts <revision> > prisma/migrations/<name>/migration.sql
 * Idempotent and careful: only HINTEK's draft still at <revision> (untouched since the previous deploy) is published,
 * a version with the same content is never created twice, and a draft the superadmin has changed is left alone.
 */
import { createHash } from "node:crypto";
import { kfidForm } from "../../lib/workflow/builtin-kfid-form";
import { riskForm } from "../../lib/workflow/builtin-risk-form";
import { formDocumentSchema } from "../../lib/workflow/form-document";

const literal = (value: string) => `'${value.replace(/'/g, "''")}'`;
const actor = "system:hintek";
const revision = Number(process.argv[2] || 3);

const lines = [
  "-- HINTEK's originals of Kontroll före idrifttagning and Riskbedömning are published as forms (Daniel 2026-09-28: no drafts, all originals).",
  "-- Generated by scripts/forms/builtin-originals-publish-migration.ts from lib/workflow/builtin-kfid-form.ts and builtin-risk-form.ts.",
  `-- Only HINTEK's draft still at revision ${revision} is published, and a version with the same content is never created twice.`,
];
for (const form of [kfidForm, riskForm]) {
  // The same hash the server computes when it publishes: the parsed document, serialised in schema order.
  const hash = createHash("sha256").update(JSON.stringify(formDocumentSchema.parse(form.document))).digest("hex");
  const template = literal(form.id);
  const versionOf = `(SELECT "version" FROM "FormTemplateVersion" WHERE "templateId" = ${template} AND "hash" = ${literal(hash)})`;
  lines.push("",
    `INSERT INTO "FormTemplateVersion" ("id", "templateId", "version", "name", "displayName", "description", "color", "icon", "category", "allowStandalone", "allowInProject", "document", "hash", "publishedBy", "publisherName", "createdAt")`,
    `SELECT ${literal(`${form.id}-published-${hash.slice(0, 12)}`)}, "id", (SELECT COALESCE(MAX("version"), 0) + 1 FROM "FormTemplateVersion" WHERE "templateId" = ${template}), "name", "displayName", "description", "color", "icon", "category", "allowStandalone", "allowInProject", "draft", ${literal(hash)}, ${literal(actor)}, 'HINTEK', CURRENT_TIMESTAMP`,
    `FROM "FormTemplate" WHERE "id" = ${template} AND "organizationId" IS NULL AND "draftRevision" = ${revision} AND "updatedBy" = ${literal(actor)}`,
    `AND NOT EXISTS (SELECT 1 FROM "FormTemplateVersion" WHERE "templateId" = ${template} AND "hash" = ${literal(hash)});`,
    `UPDATE "FormTemplate" SET "status" = 'PUBLISHED', "publishedVersion" = ${versionOf}, "updatedBy" = ${literal(actor)}, "updatedAt" = CURRENT_TIMESTAMP`,
    `WHERE "id" = ${template} AND "organizationId" IS NULL AND "updatedBy" = ${literal(actor)} AND EXISTS ${versionOf} AND "publishedVersion" IS DISTINCT FROM ${versionOf};`,
    `INSERT INTO "FormTemplateEvent" ("id", "templateId", "action", "summary", "actorUserId", "actorName", "createdAt")`,
    `SELECT ${literal(`${form.id}-published-${hash.slice(0, 12)}`)}, ${template}, 'PUBLISHED', 'Version ' || ${versionOf} || ' publicerades: HINTEK:s original ersätter den inbyggda typen', ${literal(actor)}, 'HINTEK', CURRENT_TIMESTAMP`,
    `WHERE EXISTS ${versionOf} AND NOT EXISTS (SELECT 1 FROM "FormTemplateEvent" WHERE "id" = ${literal(`${form.id}-published-${hash.slice(0, 12)}`)});`,
  );
}
process.stdout.write(`${lines.join("\n")}\n`);
